import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { CheckCircle2, Clock3, Loader2, XCircle } from "lucide-react";
import { AppPage, PageLoader } from "@/components/dashboard/app-page";
import { supabase } from "@/integrations/supabase/client";
import { naira } from "@/lib/format";

export const Route = createFileRoute("/withdrawal-processing")({ ssr:false, component: WithdrawalProcessingPage });
type Req={status:string;amount:number;reference:string;admin_note:string|null};
function WithdrawalProcessingPage(){const navigate=useNavigate();const[loading,setLoading]=useState(true);const[req,setReq]=useState<Req|null>(null);useEffect(()=>{let alive=true;const load=async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user)return navigate({to:"/login",replace:true});const{data}=await supabase.from("withdrawals").select("status, amount, reference, admin_note").eq("user_id",auth.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!alive)return;const r=data as Req|null;setReq(r);setLoading(false);if(r?.status==="completed"||r?.status==="approved")navigate({to:"/withdrawal-confirmation",replace:true});};void load();const t=window.setInterval(()=>void load(),5000);return()=>{alive=false;window.clearInterval(t)}} , [navigate]);if(loading)return <PageLoader/>;if(req?.status==="rejected")return <AppPage title="Withdrawal Request" subtitle="Action required"><section className="rounded-3xl border border-destructive/40 bg-destructive/10 p-6 text-center"><XCircle className="mx-auto h-12 w-12 text-destructive"/><h2 className="mt-3 text-xl font-extrabold">Withdrawal Rejected</h2><p className="mt-2 text-sm text-foreground/80">{req.admin_note||"Your withdrawal request was rejected. Please review the reason and submit a new request if appropriate."}</p><button onClick={()=>navigate({to:"/withdraw"})} className="mt-5 w-full rounded-xl bg-gold-gradient py-3 text-xs font-bold text-gold-foreground">Back to Withdraw</button></section></AppPage>;return <AppPage title="Withdrawal Processing" subtitle="Your payout request is under review"><section className="rounded-3xl border border-gold/40 bg-gradient-to-br from-navy via-card to-navy-deep p-7 text-center shadow-gold-glow"><Clock3 className="mx-auto h-16 w-16 animate-pulse text-gold"/><h2 className="mt-5 text-xl font-extrabold">Withdrawal Processing</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Your withdrawal request has been received. Our team is processing it and your balance has been moved to pending until the request is completed.</p>{req&&<p className="mt-4 font-display text-2xl font-extrabold text-gold">{naira(req.amount)}</p>}<p className="mt-2 text-[10px] text-muted-foreground">Reference: {req?.reference??"—"}</p><div className="mt-5 flex items-center justify-center gap-2 text-[10px] text-muted-foreground"><Loader2 className="h-3.5 w-3.5 animate-spin text-gold"/> Checking status automatically</div><button onClick={()=>navigate({to:"/requests"})} className="mt-6 w-full rounded-xl border border-border bg-background/40 py-3 text-xs font-semibold">View request history</button></section></AppPage>}
