/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalProcessingRouteImport } from './routes/withdrawal-processing'
import { Route as WithdrawalConfirmationRouteImport } from './routes/withdrawal-confirmation'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UpgradeProcessingRouteImport } from './routes/upgrade-processing'
import { Route as UpgradeConfirmationRouteImport } from './routes/upgrade-confirmation'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TapRouteImport } from './routes/tap'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CongratulationsRouteImport } from './routes/congratulations'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivationProcessingRouteImport } from './routes/activation-processing'
import { Route as ActivationConfirmationRouteImport } from './routes/activation-confirmation'
import { Route as ActivateConfirmationRouteImport } from './routes/activate-confirmation'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpgradeLevelRouteImport } from './routes/upgrade_.$level'
import { Route as ApiAiChatRouteImport } from './routes/api.ai.chat'

const WithdrawalProcessingRoute = WithdrawalProcessingRouteImport.update({
  id: '/withdrawal-processing',
  path: '/withdrawal-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalConfirmationRoute = WithdrawalConfirmationRouteImport.update({
  id: '/withdrawal-confirmation',
  path: '/withdrawal-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeProcessingRoute = UpgradeProcessingRouteImport.update({
  id: '/upgrade-processing',
  path: '/upgrade-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeConfirmationRoute = UpgradeConfirmationRouteImport.update({
  id: '/upgrade-confirmation',
  path: '/upgrade-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TapRoute = TapRouteImport.update({
  id: '/tap',
  path: '/tap',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CongratulationsRoute = CongratulationsRouteImport.update({
  id: '/congratulations',
  path: '/congratulations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationProcessingRoute = ActivationProcessingRouteImport.update({
  id: '/activation-processing',
  path: '/activation-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationConfirmationRoute = ActivationConfirmationRouteImport.update({
  id: '/activation-confirmation',
  path: '/activation-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateConfirmationRoute = ActivateConfirmationRouteImport.update({
  id: '/activate-confirmation',
  path: '/activate-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeLevelRoute = UpgradeLevelRouteImport.update({
  id: '/upgrade_/$level',
  path: '/upgrade/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-confirmation': typeof ActivateConfirmationRoute
  '/activation-confirmation': typeof ActivationConfirmationRoute
  '/activation-processing': typeof ActivationProcessingRoute
  '/admin': typeof AdminRoute
  '/congratulations': typeof CongratulationsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/surveys': typeof SurveysRoute
  '/tap': typeof TapRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/upgrade': typeof UpgradeRoute
  '/upgrade-confirmation': typeof UpgradeConfirmationRoute
  '/upgrade-processing': typeof UpgradeProcessingRoute
  '/videos': typeof VideosRoute
  '/withdraw': typeof WithdrawRoute
  '/withdrawal-confirmation': typeof WithdrawalConfirmationRoute
  '/withdrawal-processing': typeof WithdrawalProcessingRoute
  '/upgrade/$level': typeof UpgradeLevelRoute
  '/api/ai/chat': typeof ApiAiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-confirmation': typeof ActivateConfirmationRoute
  '/activation-confirmation': typeof ActivationConfirmationRoute
  '/activation-processing': typeof ActivationProcessingRoute
  '/admin': typeof AdminRoute
  '/congratulations': typeof CongratulationsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/surveys': typeof SurveysRoute
  '/tap': typeof TapRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/upgrade': typeof UpgradeRoute
  '/upgrade-confirmation': typeof UpgradeConfirmationRoute
  '/upgrade-processing': typeof UpgradeProcessingRoute
  '/videos': typeof VideosRoute
  '/withdraw': typeof WithdrawRoute
  '/withdrawal-confirmation': typeof WithdrawalConfirmationRoute
  '/withdrawal-processing': typeof WithdrawalProcessingRoute
  '/upgrade/$level': typeof UpgradeLevelRoute
  '/api/ai/chat': typeof ApiAiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-confirmation': typeof ActivateConfirmationRoute
  '/activation-confirmation': typeof ActivationConfirmationRoute
  '/activation-processing': typeof ActivationProcessingRoute
  '/admin': typeof AdminRoute
  '/congratulations': typeof CongratulationsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/surveys': typeof SurveysRoute
  '/tap': typeof TapRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/upgrade': typeof UpgradeRoute
  '/upgrade-confirmation': typeof UpgradeConfirmationRoute
  '/upgrade-processing': typeof UpgradeProcessingRoute
  '/videos': typeof VideosRoute
  '/withdraw': typeof WithdrawRoute
  '/withdrawal-confirmation': typeof WithdrawalConfirmationRoute
  '/withdrawal-processing': typeof WithdrawalProcessingRoute
  '/upgrade_/$level': typeof UpgradeLevelRoute
  '/api/ai/chat': typeof ApiAiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/activate-confirmation'
    | '/activation-confirmation'
    | '/activation-processing'
    | '/admin'
    | '/congratulations'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/questionnaire'
    | '/referrals'
    | '/register'
    | '/requests'
    | '/reset-password'
    | '/support'
    | '/surveys'
    | '/tap'
    | '/tasks'
    | '/terms'
    | '/transactions'
    | '/upgrade'
    | '/upgrade-confirmation'
    | '/upgrade-processing'
    | '/videos'
    | '/withdraw'
    | '/withdrawal-confirmation'
    | '/withdrawal-processing'
    | '/upgrade/$level'
    | '/api/ai/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/activate-confirmation'
    | '/activation-confirmation'
    | '/activation-processing'
    | '/admin'
    | '/congratulations'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/questionnaire'
    | '/referrals'
    | '/register'
    | '/requests'
    | '/reset-password'
    | '/support'
    | '/surveys'
    | '/tap'
    | '/tasks'
    | '/terms'
    | '/transactions'
    | '/upgrade'
    | '/upgrade-confirmation'
    | '/upgrade-processing'
    | '/videos'
    | '/withdraw'
    | '/withdrawal-confirmation'
    | '/withdrawal-processing'
    | '/upgrade/$level'
    | '/api/ai/chat'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/activate-confirmation'
    | '/activation-confirmation'
    | '/activation-processing'
    | '/admin'
    | '/congratulations'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/promotions'
    | '/questionnaire'
    | '/referrals'
    | '/register'
    | '/requests'
    | '/reset-password'
    | '/support'
    | '/surveys'
    | '/tap'
    | '/tasks'
    | '/terms'
    | '/transactions'
    | '/upgrade'
    | '/upgrade-confirmation'
    | '/upgrade-processing'
    | '/videos'
    | '/withdraw'
    | '/withdrawal-confirmation'
    | '/withdrawal-processing'
    | '/upgrade_/$level'
    | '/api/ai/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  ActivateConfirmationRoute: typeof ActivateConfirmationRoute
  ActivationConfirmationRoute: typeof ActivationConfirmationRoute
  ActivationProcessingRoute: typeof ActivationProcessingRoute
  AdminRoute: typeof AdminRoute
  CongratulationsRoute: typeof CongratulationsRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  ReferralsRoute: typeof ReferralsRoute
  RegisterRoute: typeof RegisterRoute
  RequestsRoute: typeof RequestsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  SurveysRoute: typeof SurveysRoute
  TapRoute: typeof TapRoute
  TasksRoute: typeof TasksRoute
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  UpgradeRoute: typeof UpgradeRoute
  UpgradeConfirmationRoute: typeof UpgradeConfirmationRoute
  UpgradeProcessingRoute: typeof UpgradeProcessingRoute
  VideosRoute: typeof VideosRoute
  WithdrawRoute: typeof WithdrawRoute
  WithdrawalConfirmationRoute: typeof WithdrawalConfirmationRoute
  WithdrawalProcessingRoute: typeof WithdrawalProcessingRoute
  UpgradeLevelRoute: typeof UpgradeLevelRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawal-processing': {
      id: '/withdrawal-processing'
      path: '/withdrawal-processing'
      fullPath: '/withdrawal-processing'
      preLoaderRoute: typeof WithdrawalProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawal-confirmation': {
      id: '/withdrawal-confirmation'
      path: '/withdrawal-confirmation'
      fullPath: '/withdrawal-confirmation'
      preLoaderRoute: typeof WithdrawalConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade-processing': {
      id: '/upgrade-processing'
      path: '/upgrade-processing'
      fullPath: '/upgrade-processing'
      preLoaderRoute: typeof UpgradeProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade-confirmation': {
      id: '/upgrade-confirmation'
      path: '/upgrade-confirmation'
      fullPath: '/upgrade-confirmation'
      preLoaderRoute: typeof UpgradeConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tap': {
      id: '/tap'
      path: '/tap'
      fullPath: '/tap'
      preLoaderRoute: typeof TapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congratulations': {
      id: '/congratulations'
      path: '/congratulations'
      fullPath: '/congratulations'
      preLoaderRoute: typeof CongratulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation-processing': {
      id: '/activation-processing'
      path: '/activation-processing'
      fullPath: '/activation-processing'
      preLoaderRoute: typeof ActivationProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation-confirmation': {
      id: '/activation-confirmation'
      path: '/activation-confirmation'
      fullPath: '/activation-confirmation'
      preLoaderRoute: typeof ActivationConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate-confirmation': {
      id: '/activate-confirmation'
      path: '/activate-confirmation'
      fullPath: '/activate-confirmation'
      preLoaderRoute: typeof ActivateConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade_/$level': {
      id: '/upgrade_/$level'
      path: '/upgrade/$level'
      fullPath: '/upgrade/$level'
      preLoaderRoute: typeof UpgradeLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  ActivateConfirmationRoute: ActivateConfirmationRoute,
  ActivationConfirmationRoute: ActivationConfirmationRoute,
  ActivationProcessingRoute: ActivationProcessingRoute,
  AdminRoute: AdminRoute,
  CongratulationsRoute: CongratulationsRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  ReferralsRoute: ReferralsRoute,
  RegisterRoute: RegisterRoute,
  RequestsRoute: RequestsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  SurveysRoute: SurveysRoute,
  TapRoute: TapRoute,
  TasksRoute: TasksRoute,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  UpgradeRoute: UpgradeRoute,
  UpgradeConfirmationRoute: UpgradeConfirmationRoute,
  UpgradeProcessingRoute: UpgradeProcessingRoute,
  VideosRoute: VideosRoute,
  WithdrawRoute: WithdrawRoute,
  WithdrawalConfirmationRoute: WithdrawalConfirmationRoute,
  WithdrawalProcessingRoute: WithdrawalProcessingRoute,
  UpgradeLevelRoute: UpgradeLevelRoute,
  ApiAiChatRoute: ApiAiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
